#!/bin/bash
# hooks/build

# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"

docker build \
  --build-arg GITHUB_TOKEN=$GITHUB_TOKEN
  -t $IMAGE_NAME .